-- Users
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('8cf28343-7b32-4365-8c04-305f342a2cee', 'john_doe', 'john.doe@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'John', 'Doe', '123', '123 Main St', 'Anytown', '12345', 'USA', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('c4e8c95e-682b-440d-b6d5-6297f0d13633', 'jane_smith', 'jane.smith@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Jane', 'Smith', '456', '456 Elm St', 'Othertown', '67890', 'USA', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('c5c180f1-bd25-443e-8f8a-924ddf13f971', 'alice_jones', 'alice.jones@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Alice', 'Jones', '789', '789 Oak St', 'Somewhere', '54321', 'Canada', 'fr', '', false, true);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('593e726d-14b1-477e-967c-72bec8478a45', 'bob_brown', 'bob.brown@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Bob', 'Brown', '101', '101 Pine St', 'Nowhere', '98765', 'Mexico', 'es', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('331f5b7e-3acd-4e91-b64d-9fee522b5f31', 'emily_davis', 'emily.davis@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Emily', 'Davis', '202', '202 Cedar St', 'Anothertown', '24680', 'Germany', 'de', 'https://example.com/avatars/emily_davis.jpg', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('56f91978-04c8-4142-93e4-706c5d23dacf', 'michael_wilson', 'michael.wilson@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Michael', 'Wilson', '303', '303 Birch St', 'Somecity', '13579', 'Spain', 'es', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('d4562dfd-2d98-4db0-9937-33fccd90599a', 'olivia_martinez', 'olivia.martinez@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Olivia', 'Martinez', '404', '404 Maple St', 'Anothercity', '24680', 'France', 'fr', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('a42d1145-cb3a-4088-a9f8-eba1310a9e80', 'david_lee', 'david.lee@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'David', 'Lee', '505', '505 Oak St', 'Somewhere', '12345', 'China', 'zh', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('26be1301-4121-4497-80d1-e448fdef0532', 'sophia_garcia', 'sophia.garcia@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Sophia', 'Garcia', '606', '606 Pine St', 'Nowhere', '67890', 'Spain', 'es', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('f336a25e-7bed-4f44-a360-f758aecd7d09', 'charlie_rodriguez', 'charlie.rodriguez@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Charlie', 'Rodriguez', '707', '707 Cedar St', 'Anothertown', '54321', 'Mexico', 'es', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('f71c870e-9daa-4991-accd-61f3c3c14fa2', 'me', 'me@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Me', 'Me', '808', '808 Birch St', 'Somewhere', '12345', 'USA', 'en', 'https://mdbcdn.b-cdn.net/img/new/avatars/2.webp', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('1968032b-4a3f-4044-bbf3-947b0c96f7a0', 'ava_walker', 'ava.walker@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Ava', 'Walker', '909', '909 Cedar St', 'Anothertown', '67890', 'USA', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('ce5578e6-87cf-44a0-877e-87c264dd281c', 'noah_turner', 'noah.turner@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Noah', 'Turner', '1010', '1010 Pine St', 'Nowhere', '54321', 'USA', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('a668f324-debb-4cf0-a543-10a8ce7ed8e2', 'mia_hall', 'mia.hall@example.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Mia', 'Hall', '1111', '1111 Oak St', 'Somewhere', '12345', 'USA', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('ff25a41d-a417-416c-9feb-dd61a7fcb2d6', 'qcastel', 'quentincastel86@gmail.com', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Quentin', 'Castel', '', '119 route des oriolleres', 'Mignaloux-Beauvoir', '86550', 'France', 'en', '', true, false);
INSERT INTO users (id, username, email, password, first_name, last_name, flat_number, street_address, city, postal_code, country, preferred_language, avatar_url, is_email_verified, disabled) VALUES ('44816124-d6cf-4bb4-a011-4847722c9e60', 'afrancani', 'allan.francani@pm.me', '$2a$10$FZLU/ajV2PZmD9cXiZqNMuruo592lNW13uKcICG5oEBdnfYNbej1e', 'Allan', 'Francani', '', '', 'Haut-Savoie', '74100', 'France', 'en', '', true, false);
